getwd()
list.files()
df<-read.csv("income.csv", stringsAsFactors=FALSE)
summary(df)
names(df)<-c("ID","CSD", "income", "growth")
df3<-subset(df, ID==3)
df2<-subset(df, ID==2)
summary(df3, df2)

plot(density(df3$income, na.rm = T))
plot(density(df2$income, na.rm = T))
plot()
summary("df$income")
boxplot(income~ID, data = df, main="incm data", xlab="location", ylab="incm")
