install.packages("mongolite")
require("mongolite")
articles<-mongo(collection="articles", url="mongodb://Gareth:funkyk200@ds047095.mongolab.com:47095/newsnet")
articles$count()
data<-articles$find()
require("jsonlite")
text<-toJSON(data)
page<-articles$iterate$batch()
articles$export()
cat(text, file="C:/texts/text")
